version: '3.8'
services:
  redis:
    build:
      context: ./redis
      dockerfile: dockerfile
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - general_network
    mem_limit: 124M
    mem_reservation: 50M
    cpus: "0.4"

  bot:
    build:
      context: ./src
      dockerfile: dockerfile
    container_name: bot
    environment:
      - tg_token=${tg_token}
      - sender_email=${sender_email}
      - recipient_email=${recipient_email}
      - email_password=${email_password}
    networks:
      - general_network
    mem_limit: 124M
    mem_reservation: 20M
    cpus: "0.5"

networks:
  general_network:
    driver: bridge
