name: Workflow

on:
  push:
    branches: [main]

env:
  project_path: $project_path
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Redis Image
        run: |
          docker build ./redis --tag ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application_redis:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application_redis:latest

      - name: Build and Push Bot Image
        run: |
          docker build ./src --tag ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to VM
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        port: ${{ secrets.VM_SSH_PORT }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "./docker-compose.yml"
        target: $project_path

    - name: Copy Makefile to VM
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        port: ${{ secrets.VM_SSH_PORT }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "./makefile"
        target: $project_path

    - name: Restart containers on VM
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: ${{ secrets.VM_SSH_PORT }}
        script: |
          cd $project_path
          touch .env
          echo '
          tg_token=${{ secrets.TG_TOKEN }}
          sender_email=$SENDER_EMAIL
          recipient_email=$RECIPIENT_EMAIL
          email_password=${{ secrets.EMAIL_PASSWORD }}
          ' > .env
          make ENVIRONMENT=production up
