name: Workflow

on:
  push:
    branches: [main]

env:
  tg_token: ${{ secrets.TG_TOKEN }}
  sender_email: $SENDER_EMAIL
  recipient_email: $RECIPIENT_EMAIL
  email_password: ${{ secrets.EMAIL_PASSWORD }}

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
            cli-args: "up --build"
