name: Workflow

on:
  push:
    branches: [main]

env:
  tg_token: ${{ secrets.TG_TOKEN }}
  sender_email: $SENDER_EMAIL
  recipient_email: $RECIPIENT_EMAIL
  email_password: ${{ secrets.EMAIL_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Redis Image
        run: |
          docker build ./redis --tag ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application_redis:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application_redis:latest

      - name: Build and Push Bot Image
        run: |
          docker build ./src --tag ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tg_bot_application:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to VM
      uses: appleboy/scp-action@v0.1.3
      with:
        source: "./docker-compose.yml"
        target: ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/bicho/deployed_projects/tgbot_application/
        key: ${{ secrets.VM_SSH_KEY }}

    - name: Copy Makefile to VM
      uses: appleboy/scp-action@v0.1.3
      with:
        source: "./makefile"
        target: ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/bicho/deployed_projects/tgbot_application/
        key: ${{ secrets.VM_SSH_KEY }}

    - name: Restart containers on VM
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd /path/to/your/project
          make ENVIRONMENT=production up
